// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Contract struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	IsContract bool      `json:"is_contract"`
	ChainID    string    `json:"chain_id"`
	Address    string    `json:"address"`
	Network    string    `json:"network"`
	CreatedAt  time.Time `json:"created_at"`
}

type Email struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

type EmailsContract struct {
	ID         int64     `json:"id"`
	EmailID    int64     `json:"email_id"`
	ContractID int64     `json:"contract_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type TokensContract struct {
	ID         int64     `json:"id"`
	ContractID int64     `json:"contract_id"`
	Name       string    `json:"name"`
	Symbol     string    `json:"symbol"`
	Address    string    `json:"address"`
	Decimals   int64     `json:"decimals"`
	UpdatedAt  time.Time `json:"updated_at"`
}
